// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0_ppNikrOxJsPRgT-L_Yi0bhpqx-khss',
    appId: '1:442032355185:web:ba86dfbd1dd1ebaa10a8d0',
    messagingSenderId: '442032355185',
    projectId: 'dempro-7db5d',
    authDomain: 'dempro-7db5d.firebaseapp.com',
    storageBucket: 'dempro-7db5d.firebasestorage.app',
    measurementId: 'G-QZDBSH4HZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9uV0jzqxvXc5bnzTSNs6m2EEWMgLelQ',
    appId: '1:442032355185:android:64d44342bad365b210a8d0',
    messagingSenderId: '442032355185',
    projectId: 'dempro-7db5d',
    storageBucket: 'dempro-7db5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCApUWifA9hcnEpTZYomudJv09GdYTHGqU',
    appId: '1:442032355185:ios:16c75a3f3e0c484b10a8d0',
    messagingSenderId: '442032355185',
    projectId: 'dempro-7db5d',
    storageBucket: 'dempro-7db5d.firebasestorage.app',
    iosBundleId: 'com.example.dempro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCApUWifA9hcnEpTZYomudJv09GdYTHGqU',
    appId: '1:442032355185:ios:16c75a3f3e0c484b10a8d0',
    messagingSenderId: '442032355185',
    projectId: 'dempro-7db5d',
    storageBucket: 'dempro-7db5d.firebasestorage.app',
    iosBundleId: 'com.example.dempro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0_ppNikrOxJsPRgT-L_Yi0bhpqx-khss',
    appId: '1:442032355185:web:da65371751d192d610a8d0',
    messagingSenderId: '442032355185',
    projectId: 'dempro-7db5d',
    authDomain: 'dempro-7db5d.firebaseapp.com',
    storageBucket: 'dempro-7db5d.firebasestorage.app',
    measurementId: 'G-V0GD84MKDB',
  );

}